### ISSUE TITLE
make a super simple video tutorial

### ISSUE THREAD

**Issue by solidpulse** [kejojedi/breeze#1]
I like the idea but, no idea how to use this.
may be a better description of what it does, the readme doesn't even tell me the what and why?
making a super simple video tutorial may be useful.

**Comment by kejojedi** [comment]
this is planned for later :)

for now, just check out the `/app` folder to see how it works.

declare the route using the `route()` function, the framework automatically generates the routes by going through the files and checking the value within that function.
